services:
  ark:
    container_name: ark
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=Ark Docker
      - SERVERMAP=TheIsland
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=12456
      - BACKUPONSTART=1
      - UPDATEONSTART=1
      - TZ=America/New_York
      - GID=1000
      - UID=1000
    volumes:
      - /ark/the_island:/ark
    ports:
    - 7778:7778/udp
    - 7778:7778
    - 27015:27015/udp
    - 27015:27015
    - 32330:32330
