volumes:
  ark_volume:

services:
  the_island:
    container_name: TheIsland
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=FunTimes
      - SERVERMAP=TheIsland
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=1234
      - BACKUPONSTART=1
      - UPDATEONSTART=1
      - TZ=America/New_York
      - CLUSTERID=dep_cluster
    volumes:
      - ark_volume:/ark
    ports:
    - 7777:7777
    - 7777:7777/udp
    - 7778:7778
    - 7778:7778/udp
    - 27015:27015
    - 27015:27015/udp
    - 27020:32330
