services:
  the_island:
    container_name: TheIsland
    mem_limit: 8g
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=FunTimes
      - SERVERMAP=TheIsland
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=1234
      - BACKUPONSTART=0
      - UPDATEONSTART=1
      - TZ=America/New_York
      - CLUSTERID=dep_cluster
      - GAMECLIENTPORT=7777
      - SERVERPORT=7778
      - STEAMPORT=27015
    volumes:
      - ark_volume:/ark
    ports:
    - 7777:7777
    - 7777:7777/udp
    - 7778:7778
    - 7778:7778/udp
    - 27015:27015
    - 27015:27015/udp
    - 27020:32330
  scorched_earth:
    container_name: ScorchedEarth
    mem_limit: 8g
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=FunTimes
      - SERVERMAP=ScorchedEarth_P
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=1234
      - BACKUPONSTART=0
      - UPDATEONSTART=1
      - TZ=America/New_York
      - CLUSTERID=dep_cluster
      - GAMECLIENTPORT=9999
      - SERVERPORT=10000
      - STEAMPORT=37015
    volumes:
      - ark_volume:/ark
    ports:
    - 9999:9999
    - 9999:9999/udp
    - 10000:10000
    - 10000:10000/udp
    - 37015:37015
    - 37015:37015/udp
    - 37016:32330
  the_center:
    container_name: TheCenter
    mem_limit: 8g
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=FunTimes
      - SERVERMAP=TheCenter
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=1234
      - BACKUPONSTART=0
      - UPDATEONSTART=1
      - TZ=America/New_York
      - CLUSTERID=dep_cluster
    volumes:
      - ark_volume:/ark
    ports:
    - 7777:7777
    - 7777:7777/udp
    - 7778:7778
    - 7778:7778/udp
    - 27015:27015
    - 27015:27015/udp
    - 32330:32330
  ragnarok:
    container_name: Ragnarok
    mem_limit: 8g
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=FunTimes
      - SERVERMAP=Ragnarok
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=1234
      - BACKUPONSTART=0
      - UPDATEONSTART=1
      - TZ=America/New_York
      - CLUSTERID=dep_cluster
    volumes:
      - ark_volume:/ark
    ports:
    - 7777:7777
    - 7777:7777/udp
    - 7778:7778
    - 7778:7778/udp
    - 27015:27015
    - 27015:27015/udp
    - 32330:32330
  aberration:
    container_name: Aberration
    mem_limit: 8g
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=FunTimes
      - SERVERMAP=Aberration_P
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=1234
      - BACKUPONSTART=0
      - UPDATEONSTART=1
      - TZ=America/New_York
      - CLUSTERID=dep_cluster
      - GAMECLIENTPORT=7779
      - SERVERPORT=7780
      - STEAMPORT=27016
    volumes:
      - ark_volume:/ark
    ports:
    - 7779:7779
    - 7779:7779/udp
    - 7780:7780
    - 7780:7780/udp
    - 27016:27016
    - 27016:27016/udp
    - 27021:32330
  extinction:
    container_name: Extinction
    mem_limit: 8g
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=FunTimes
      - SERVERMAP=Extinction
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=1234
      - BACKUPONSTART=0
      - UPDATEONSTART=1
      - TZ=America/New_York
      - CLUSTERID=dep_cluster
      - GAMECLIENTPORT=7781
      - SERVERPORT=7782
      - STEAMPORT=27017
    volumes:
      - ark_volume:/ark
    ports:
    - 7781:7781
    - 7781:7781/udp
    - 7782:7782
    - 7782:7782/udp
    - 27017:27017
    - 27017:27017/udp
    - 27022:32330
  valguero:
    container_name: Valguero
    mem_limit: 8g
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=FunTimes
      - SERVERMAP=Valguero_P
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=1234
      - BACKUPONSTART=0
      - UPDATEONSTART=1
      - TZ=America/New_York
      - CLUSTERID=dep_cluster
    volumes:
      - ark_volume:/ark
    ports:
    - 7777:7777
    - 7777:7777/udp
    - 7778:7778
    - 7778:7778/udp
    - 27015:27015
    - 27015:27015/udp
    - 32330:32330
  lost_island:
    container_name: LostIsland
    mem_limit: 8g
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=FunTimes
      - SERVERMAP=LostIsland
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=1234
      - BACKUPONSTART=0
      - UPDATEONSTART=1
      - TZ=America/New_York
      - CLUSTERID=dep_cluster
    volumes:
      - ark_volume:/ark
    ports:
    - 7777:7777
    - 7777:7777/udp
    - 7778:7778
    - 7778:7778/udp
    - 27015:27015
    - 27015:27015/udp
    - 32330:32330
  fjordu:
    container_name: Fjordur
    mem_limit: 8g
    restart: always
    build:
      dockerfile: Dockerfile
    environment:
      - SESSIONNAME=FunTimes
      - SERVERMAP=Fjordur
      - SERVERPASSWORD=12456
      - ADMINPASSWORD=1234
      - BACKUPONSTART=0
      - UPDATEONSTART=1
      - TZ=America/New_York
      - CLUSTERID=dep_cluster
    volumes:
      - ark_volume:/ark
    ports:
    - 7777:7777
    - 7777:7777/udp
    - 7778:7778
    - 7778:7778/udp
    - 27015:27015
    - 27015:27015/udp
    - 32330:32330

volumes:
  ark_volume:
